//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_WinForm_client.Lab4ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://svv/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://svv/", ConfigurationName="Lab4ServiceReference.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_1) сообщения Sum_1 не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://svv/Sum_1", ReplyAction="*")]
        Lab4_WinForm_client.Lab4ServiceReference.Sum_11 Add(Lab4_WinForm_client.Lab4ServiceReference.Sum_1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv/Sum_1", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_11> AddAsync(Lab4_WinForm_client.Lab4ServiceReference.Sum_1 request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_2) сообщения Sum_2 не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://svv/Sum_2", ReplyAction="*")]
        Lab4_WinForm_client.Lab4ServiceReference.Sum_21 Concat(Lab4_WinForm_client.Lab4ServiceReference.Sum_2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv/Sum_2", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_21> ConcatAsync(Lab4_WinForm_client.Lab4ServiceReference.Sum_2 request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_3) сообщения Sum_3 не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://svv/Sum_3", ReplyAction="*")]
        Lab4_WinForm_client.Lab4ServiceReference.Sum_31 Sum(Lab4_WinForm_client.Lab4ServiceReference.Sum_3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv/Sum_3", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_31> SumAsync(Lab4_WinForm_client.Lab4ServiceReference.Sum_3 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_1", WrapperNamespace="http://svv/", IsWrapped=true)]
    public partial class Sum_1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=1)]
        public int y;
        
        public Sum_1() {
        }
        
        public Sum_1(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_1Response", WrapperNamespace="http://svv/", IsWrapped=true)]
    public partial class Sum_11 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=0)]
        public int Sum_1Result;
        
        public Sum_11() {
        }
        
        public Sum_11(int Sum_1Result) {
            this.Sum_1Result = Sum_1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_2", WrapperNamespace="http://svv/", IsWrapped=true)]
    public partial class Sum_2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=1)]
        public double d;
        
        public Sum_2() {
        }
        
        public Sum_2(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_2Response", WrapperNamespace="http://svv/", IsWrapped=true)]
    public partial class Sum_21 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=0)]
        public string Sum_2Result;
        
        public Sum_21() {
        }
        
        public Sum_21(string Sum_2Result) {
            this.Sum_2Result = Sum_2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_3", WrapperNamespace="http://svv/", IsWrapped=true)]
    public partial class Sum_3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=0)]
        public Lab4_WinForm_client.Lab4ServiceReference.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=1)]
        public Lab4_WinForm_client.Lab4ServiceReference.A a2;
        
        public Sum_3() {
        }
        
        public Sum_3(Lab4_WinForm_client.Lab4ServiceReference.A a1, Lab4_WinForm_client.Lab4ServiceReference.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_3Response", WrapperNamespace="http://svv/", IsWrapped=true)]
    public partial class Sum_31 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://svv/", Order=0)]
        public Lab4_WinForm_client.Lab4ServiceReference.A Sum_3Result;
        
        public Sum_31() {
        }
        
        public Sum_31(Lab4_WinForm_client.Lab4ServiceReference.A Sum_3Result) {
            this.Sum_3Result = Sum_3Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap>, Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_WinForm_client.Lab4ServiceReference.Sum_11 Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap.Add(Lab4_WinForm_client.Lab4ServiceReference.Sum_1 request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            Lab4_WinForm_client.Lab4ServiceReference.Sum_1 inValue = new Lab4_WinForm_client.Lab4ServiceReference.Sum_1();
            inValue.x = x;
            inValue.y = y;
            Lab4_WinForm_client.Lab4ServiceReference.Sum_11 retVal = ((Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap)(this)).Add(inValue);
            return retVal.Sum_1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_11> Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap.AddAsync(Lab4_WinForm_client.Lab4ServiceReference.Sum_1 request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_11> AddAsync(int x, int y) {
            Lab4_WinForm_client.Lab4ServiceReference.Sum_1 inValue = new Lab4_WinForm_client.Lab4ServiceReference.Sum_1();
            inValue.x = x;
            inValue.y = y;
            return ((Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_WinForm_client.Lab4ServiceReference.Sum_21 Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap.Concat(Lab4_WinForm_client.Lab4ServiceReference.Sum_2 request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            Lab4_WinForm_client.Lab4ServiceReference.Sum_2 inValue = new Lab4_WinForm_client.Lab4ServiceReference.Sum_2();
            inValue.s = s;
            inValue.d = d;
            Lab4_WinForm_client.Lab4ServiceReference.Sum_21 retVal = ((Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap)(this)).Concat(inValue);
            return retVal.Sum_2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_21> Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap.ConcatAsync(Lab4_WinForm_client.Lab4ServiceReference.Sum_2 request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_21> ConcatAsync(string s, double d) {
            Lab4_WinForm_client.Lab4ServiceReference.Sum_2 inValue = new Lab4_WinForm_client.Lab4ServiceReference.Sum_2();
            inValue.s = s;
            inValue.d = d;
            return ((Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_WinForm_client.Lab4ServiceReference.Sum_31 Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap.Sum(Lab4_WinForm_client.Lab4ServiceReference.Sum_3 request) {
            return base.Channel.Sum(request);
        }
        
        public Lab4_WinForm_client.Lab4ServiceReference.A Sum(Lab4_WinForm_client.Lab4ServiceReference.A a1, Lab4_WinForm_client.Lab4ServiceReference.A a2) {
            Lab4_WinForm_client.Lab4ServiceReference.Sum_3 inValue = new Lab4_WinForm_client.Lab4ServiceReference.Sum_3();
            inValue.a1 = a1;
            inValue.a2 = a2;
            Lab4_WinForm_client.Lab4ServiceReference.Sum_31 retVal = ((Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap)(this)).Sum(inValue);
            return retVal.Sum_3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_31> Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap.SumAsync(Lab4_WinForm_client.Lab4ServiceReference.Sum_3 request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_WinForm_client.Lab4ServiceReference.Sum_31> SumAsync(Lab4_WinForm_client.Lab4ServiceReference.A a1, Lab4_WinForm_client.Lab4ServiceReference.A a2) {
            Lab4_WinForm_client.Lab4ServiceReference.Sum_3 inValue = new Lab4_WinForm_client.Lab4ServiceReference.Sum_3();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((Lab4_WinForm_client.Lab4ServiceReference.SimplexSoap)(this)).SumAsync(inValue);
        }
    }
}
